# Generated by Django 5.2.8 on 2025-11-16 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'MRI - Left Breast Lump'", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("awaiting_results", "Awaiting Results"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for this case"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Doctor handling this case",
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this case belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case_number"], name="cases_case_case_nu_a07304_idx"
                    ),
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="cases_case_patient_654009_idx",
                    ),
                    models.Index(
                        fields=["doctor", "-created_at"],
                        name="cases_case_doctor__b9da76_idx",
                    ),
                    models.Index(
                        fields=["status"], name="cases_case_status_5f99d2_idx"
                    ),
                ],
            },
        ),
    ]
