# Generated by Django 5.2.8 on 2025-11-16 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="cases_case_case_nu_a07304_idx",
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="cases_case_patient_654009_idx",
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="cases_case_doctor__b9da76_idx",
        ),
        migrations.RemoveIndex(
            model_name="case",
            name="cases_case_status_5f99d2_idx",
        ),
        migrations.RemoveField(
            model_name="case",
            name="case_number",
        ),
        migrations.RemoveField(
            model_name="case",
            name="description",
        ),
        migrations.RemoveField(
            model_name="case",
            name="diagnosis_date",
        ),
        migrations.RemoveField(
            model_name="case",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="case",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="case",
            name="title",
        ),
        migrations.AddField(
            model_name="case",
            name="case_code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="case",
            name="has_prediction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="has_recommendation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
