# Generated by Django 5.2.8 on 2025-11-17 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_case_options_and_more"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={},
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["patient", "case_code"], name="cases_case_patient_6aff97_idx"
            ),
        ),
    ]
