# Generated by Django 5.2.8 on 2025-12-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Risk level determined by AI prediction', max_length=20, null=True),
        ),
    ]
