# Generated by Django 5.2.8 on 2025-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True, help_text="Doctor's notes and observations about this case", null=True),
        ),
    ]
