# Generated by Django 5.2.8 on 2025-12-20 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_add_notes_field'),
        ('patients', '0003_alter_patient_dob_alter_patient_identity_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('case_code',), name='unique_active_case_code'),
        ),
    ]
