# Generated by Django 5.2.8 on 2025-12-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_options_case_unique_active_case_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
