Patients endpoint
#######################################

list all patients
#######################################
GET http://127.0.0.1:8000/api/v1/patients/
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

############################################
detil patient info
####################################### 
PATCH   http://127.0.0.1:8000/api/v1/patients/25a90a46-f3cd-44fc-953f-e26480eb8d44/
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

{
    "full_name": "Ali Hassan",
   
}
############################################

create a patient
#######################################
###
POST http://127.0.0.1:8000/api/v1/patients/
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

{
  "full_name": "Sara Mahmood",
  "dob": "1990-05-02",
  "gender": "female",
  "phone_number": "0123456789",
  "email": "sara@example.com",
  "address": "Kuala Lumpur",
  "emergency_contact_name": "Mother",
  "emergency_contact_relation": "Parent",
  "emergency_contact_phone": "0192837465",
  "medical_history": "None",
  "allergies": "None",
  "current_medications": "None",
  "assigned_doctor": "0da42c6d-8dda-4470-909c-d57d98f880be"
}




########################################



####    
update a patient
#######################################
PATCH http://

############################################
PUT url HTTP/1.1
header name: header value

content
############################################
delete a patient ( soft delete )
#######################################
DELETE http://127.0.0.1:8000/api/v1/patients/3cc7313b-d961-47c9-9b46-9f7286021d4d/
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

############################################