# Generated by Django 5.2.8 on 2025-12-09 10:48

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, storage=apps.users.models.get_minio_storage, upload_to=apps.users.models.user_profile_image_path),
        ),
    ]
