# Generated by Django 5.2.8 on 2025-12-20 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_two_factor_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.UUIDField(help_text='Original user ID before deletion')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived User',
                'verbose_name_plural': 'Archived Users',
                'db_table': 'users_user_archive',
                'ordering': ['-archived_at'],
            },
        ),
    ]
