# Generated by Django 5.2.8 on 2025-11-24 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_alter_case_options_and_more"),
        ("documents", "0002_remove_document_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HER2Prediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "her2_status",
                    models.CharField(
                        choices=[
                            ("HER2_0", "HER2 Negative (0)"),
                            ("HER2_1+", "HER2 Low Positive (1+)"),
                            ("HER2_2+", "HER2 Moderate Positive (2+)"),
                            ("HER2_3+", "HER2 High Positive (3+)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Model confidence (0.0-1.0)"),
                ),
                (
                    "probabilities",
                    models.JSONField(help_text="All class probabilities"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("risk_score", models.FloatField(help_text="Risk score (0-100)")),
                (
                    "gradcam_object_key",
                    models.CharField(
                        blank=True,
                        help_text="MinIO path to Grad-CAM heatmap",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("model_version", models.CharField(default="v2.4.1", max_length=20)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="her2_predictions",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The HER2 tissue image analyzed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="her2_predictions",
                        to="documents.document",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_her2_predictions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-created_at"],
                        name="ai_her2_pre_case_id_01d5ba_idx",
                    ),
                    models.Index(
                        fields=["document"], name="ai_her2_pre_documen_d39d11_idx"
                    ),
                    models.Index(
                        fields=["her2_status"], name="ai_her2_pre_her2_st_dbdb21_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="ai_her2_pre_risk_le_a17ed1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document",), name="unique_prediction_per_document"
                    )
                ],
            },
        ),
    ]
