# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("cases", "0003_alter_case_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True, help_text="Doctor's clinical observations and notes"
                    ),
                ),
                (
                    "patient_history_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text from uploaded history documents (OCR)",
                    ),
                ),
                (
                    "recommendation_text",
                    models.TextField(
                        help_text="Generated clinical recommendations from Gemini LLM"
                    ),
                ),
                (
                    "clinical_assessment",
                    models.TextField(
                        blank=True, help_text="LLM's clinical assessment summary"
                    ),
                ),
                (
                    "treatment_recommendations",
                    models.JSONField(
                        default=list,
                        help_text="Structured treatment recommendations (list of strings)",
                    ),
                ),
                (
                    "followup_schedule",
                    models.JSONField(
                        default=list,
                        help_text="Suggested follow-up timeline (list of strings)",
                    ),
                ),
                (
                    "risk_mitigation",
                    models.JSONField(
                        default=list,
                        help_text="Risk mitigation strategies (list of strings)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("saved", "Saved"),
                            ("discarded", "Discarded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="gemini-2.5-flash",
                        help_text="Gemini model version used",
                        max_length=50,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Case this recommendation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        help_text="HER2 prediction this recommendation is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="ai.her2prediction",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_clinical",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-created_at"],
                        name="recommendat_case_id_5b152c_idx",
                    ),
                    models.Index(
                        fields=["prediction"], name="recommendat_predict_4cdca1_idx"
                    ),
                    models.Index(
                        fields=["status"], name="recommendat_status_fefa35_idx"
                    ),
                ],
            },
        ),
    ]
