from django.db import models

from apps.common.models import BaseModel
from apps.cases.models import Case


class Document(BaseModel):
    """
    Stores metadata for any file related to a case.

    We NEVER store the binary file in the DB.
    We only store the MinIO object key + metadata.

    Typical use:
    - kind = maedical_imge  - original MRI / ultrasound / histopathology
    - kind = xai_image      - Grad-CAM / heatmap generated by AI
    - kind = report         - PDF reports or extra docs (future)
    """

    class Kind(models.TextChoices):
        MEDICAL_IMAGE = "medical_image", "Medical Image"
        XAI_IMAGE = "xai_image", "XAI Image"
        REPORT = "report", "Report"
        MEDICAL_HISTORY = "medical_history", "Medical History Document (Image or File)"

    case = models.ForeignKey(
        Case,
        related_name="documents",
        on_delete=models.CASCADE,
        help_text="Case this document belongs to.",
    )

    original_filename = models.CharField(
        max_length=255,
        blank=True,
        help_text="Original filename from upload (for display purposes).",
    )

    kind = models.CharField(
        max_length=50,
        choices=Kind.choices,
        default=Kind.MEDICAL_IMAGE,
        help_text="Type of document (medical image, XAI image, report, etc.).",
    )

    # MinIO object key, e.g.:
    #   cases/<case_uuid>/uploads/<uuid>.png
    #   cases/<case_uuid>/xai/<uuid>.png
    object_key = models.CharField(
        max_length=255,
        help_text="MinIO object key (path) used to generate signed URLs.",
    )



    mime_type = models.CharField(
        max_length=100,
        blank=True,
        help_text="MIME type, e.g. image/png, image/jpeg, application/pdf.",
    )

    size_bytes = models.PositiveBigIntegerField(
        null=True,
        blank=True,
        help_text="File size in bytes (optional, for UI / validation).",
    )


    ocr_text = models.TextField(
        blank=True,
        null=True,
        help_text="Extracted text from scanned images, PDFs, or uploaded history documents."
    )


    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["case", "kind"]),
            models.Index(fields=["object_key"]),
        ]

    def __str__(self) -> str:
        label = self.original_filename or self.object_key
        return f"{self.get_kind_display()} → {label}"
