# Generated by Django 5.2.8 on 2025-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identity_number',
            field=models.CharField(default='UNKNOWN', help_text='IC, Passport, or Identification Number', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
