# Generated by Django 5.2.8 on 2025-12-20 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_identity_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identity_number',
            field=models.CharField(help_text='IC, Passport, or Identification Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('patient_code',), name='unique_active_patient_code'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('identity_number',), name='unique_active_identity_number'),
        ),
    ]
