# Generated by Django 5.2.8 on 2025-11-18 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_alter_case_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("medical_image", "Medical Image"),
                            ("xai_image", "XAI Image"),
                            ("report", "Report"),
                            (
                                "medical_history",
                                "Medical History Document (Image or File)",
                            ),
                        ],
                        default="medical_image",
                        help_text="Type of document (medical image, XAI image, report, etc.).",
                        max_length=50,
                    ),
                ),
                (
                    "object_key",
                    models.CharField(
                        help_text="MinIO object key (path) used to generate signed URLs.",
                        max_length=255,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original file name uploaded by the user (for UI display).",
                        max_length=255,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type, e.g. image/png, image/jpeg, application/pdf.",
                        max_length=100,
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="File size in bytes (optional, for UI / validation).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional short caption/description for the document.",
                        max_length=255,
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text from scanned images, PDFs, or uploaded history documents.",
                        null=True,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Case this document belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "kind"], name="documents_d_case_id_5a3325_idx"
                    ),
                    models.Index(
                        fields=["object_key"], name="documents_d_object__4942e1_idx"
                    ),
                ],
            },
        ),
    ]
