# Generated by Django 5.2.8 on 2025-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="description",
        ),
        migrations.AlterField(
            model_name="document",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename from upload (for display purposes).",
                max_length=255,
            ),
        ),
    ]
