# Generated by Django 5.2.8 on 2025-12-03 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("save", "Save"),
                            ("discard", "Discard"),
                            ("predict", "Predict"),
                            ("generate", "Generate"),
                            ("assign", "Assign"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("patient", "Patient"),
                            ("case", "Case"),
                            ("document", "Document"),
                            ("prediction", "Prediction"),
                            ("recommendation", "Recommendation"),
                        ],
                        help_text="Type of entity affected",
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="UUID of the affected entity"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the action (e.g., changed fields, old/new values)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string from the request"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activities_user_id_7bdf29_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id", "-created_at"],
                        name="activities_entity__982a04_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="activities_action_23a5db_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="activities_created_765ec9_idx"
                    ),
                ],
            },
        ),
    ]
